const Shimmer = () => {
  return (
    <div className="shimmer-container grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6 p-4">
      <div className="shimmer-card bg-gray-200 h-40 rounded-lg shadow-lg relative overflow-hidden before:absolute before:inset-0 before:bg-gradient-to-r before:from-transparent before:via-white/50 before:to-transparent before:translate-x-full before:animate-shimmer"></div>
      <div className="shimmer-card bg-gray-200 h-40 rounded-lg shadow-lg relative overflow-hidden before:absolute before:inset-0 before:bg-gradient-to-r before:from-transparent before:via-white/50 before:to-transparent before:translate-x-full before:animate-shimmer"></div>
      <div className="shimmer-card bg-gray-200 h-40 rounded-lg shadow-lg relative overflow-hidden before:absolute before:inset-0 before:bg-gradient-to-r before:from-transparent before:via-white/50 before:to-transparent before:translate-x-full before:animate-shimmer"></div>
      <div className="shimmer-card bg-gray-200 h-40 rounded-lg shadow-lg relative overflow-hidden before:absolute before:inset-0 before:bg-gradient-to-r before:from-transparent before:via-white/50 before:to-transparent before:translate-x-full before:animate-shimmer"></div>
      <div className="shimmer-card bg-gray-200 h-40 rounded-lg shadow-lg relative overflow-hidden before:absolute before:inset-0 before:bg-gradient-to-r before:from-transparent before:via-white/50 before:to-transparent before:translate-x-full before:animate-shimmer"></div>
      <div className="shimmer-card bg-gray-200 h-40 rounded-lg shadow-lg relative overflow-hidden before:absolute before:inset-0 before:bg-gradient-to-r before:from-transparent before:via-white/50 before:to-transparent before:translate-x-full before:animate-shimmer"></div>
      <div className="shimmer-card bg-gray-200 h-40 rounded-lg shadow-lg relative overflow-hidden before:absolute before:inset-0 before:bg-gradient-to-r before:from-transparent before:via-white/50 before:to-transparent before:translate-x-full before:animate-shimmer"></div>
      <div className="shimmer-card bg-gray-200 h-40 rounded-lg shadow-lg relative overflow-hidden before:absolute before:inset-0 before:bg-gradient-to-r before:from-transparent before:via-white/50 before:to-transparent before:translate-x-full before:animate-shimmer"></div>
      <div className="shimmer-card bg-gray-200 h-40 rounded-lg shadow-lg relative overflow-hidden before:absolute before:inset-0 before:bg-gradient-to-r before:from-transparent before:via-white/50 before:to-transparent before:translate-x-full before:animate-shimmer"></div>
      <div className="shimmer-card bg-gray-200 h-40 rounded-lg shadow-lg relative overflow-hidden before:absolute before:inset-0 before:bg-gradient-to-r before:from-transparent before:via-white/50 before:to-transparent before:translate-x-full before:animate-shimmer"></div>
      <div className="shimmer-card bg-gray-200 h-40 rounded-lg shadow-lg relative overflow-hidden before:absolute before:inset-0 before:bg-gradient-to-r before:from-transparent before:via-white/50 before:to-transparent before:translate-x-full before:animate-shimmer"></div>
      <div className="shimmer-card bg-gray-200 h-40 rounded-lg shadow-lg relative overflow-hidden before:absolute before:inset-0 before:bg-gradient-to-r before:from-transparent before:via-white/50 before:to-transparent before:translate-x-full before:animate-shimmer"></div>
      <div className="shimmer-card bg-gray-200 h-40 rounded-lg shadow-lg relative overflow-hidden before:absolute before:inset-0 before:bg-gradient-to-r before:from-transparent before:via-white/50 before:to-transparent before:translate-x-full before:animate-shimmer"></div>
      <div className="shimmer-card bg-gray-200 h-40 rounded-lg shadow-lg relative overflow-hidden before:absolute before:inset-0 before:bg-gradient-to-r before:from-transparent before:via-white/50 before:to-transparent before:translate-x-full before:animate-shimmer"></div>
      <div className="shimmer-card bg-gray-200 h-40 rounded-lg shadow-lg relative overflow-hidden before:absolute before:inset-0 before:bg-gradient-to-r before:from-transparent before:via-white/50 before:to-transparent before:translate-x-full before:animate-shimmer"></div>
      <div className="shimmer-card bg-gray-200 h-40 rounded-lg shadow-lg relative overflow-hidden before:absolute before:inset-0 before:bg-gradient-to-r before:from-transparent before:via-white/50 before:to-transparent before:translate-x-full before:animate-shimmer"></div>
      <div className="shimmer-card bg-gray-200 h-40 rounded-lg shadow-lg relative overflow-hidden before:absolute before:inset-0 before:bg-gradient-to-r before:from-transparent before:via-white/50 before:to-transparent before:translate-x-full before:animate-shimmer"></div>
      <div className="shimmer-card bg-gray-200 h-40 rounded-lg shadow-lg relative overflow-hidden before:absolute before:inset-0 before:bg-gradient-to-r before:from-transparent before:via-white/50 before:to-transparent before:translate-x-full before:animate-shimmer"></div>
      <div className="shimmer-card bg-gray-200 h-40 rounded-lg shadow-lg relative overflow-hidden before:absolute before:inset-0 before:bg-gradient-to-r before:from-transparent before:via-white/50 before:to-transparent before:translate-x-full before:animate-shimmer"></div>
      <div className="shimmer-card bg-gray-200 h-40 rounded-lg shadow-lg relative overflow-hidden before:absolute before:inset-0 before:bg-gradient-to-r before:from-transparent before:via-white/50 before:to-transparent before:translate-x-full before:animate-shimmer"></div>
      <div className="shimmer-card bg-gray-200 h-40 rounded-lg shadow-lg relative overflow-hidden before:absolute before:inset-0 before:bg-gradient-to-r before:from-transparent before:via-white/50 before:to-transparent before:translate-x-full before:animate-shimmer"></div>
      <div className="shimmer-card bg-gray-200 h-40 rounded-lg shadow-lg relative overflow-hidden before:absolute before:inset-0 before:bg-gradient-to-r before:from-transparent before:via-white/50 before:to-transparent before:translate-x-full before:animate-shimmer"></div>
      <div className="shimmer-card bg-gray-200 h-40 rounded-lg shadow-lg relative overflow-hidden before:absolute before:inset-0 before:bg-gradient-to-r before:from-transparent before:via-white/50 before:to-transparent before:translate-x-full before:animate-shimmer"></div>
    </div>
  );
};

export default Shimmer;
